In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 1.4309445  -1.321634   -0.77029361 -0.03898244 -0.85468316]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 1.4309445  -1.321634   -0.77029361 -0.03898244 -0.85468316]


In [5]:
print(np.dot(a, a.T))

5.119673771250886


In [6]:
a = np.random.randn(5, 1)
print(a)

[[-0.77526548]
 [ 1.29765027]
 [-1.77532732]
 [ 0.32350956]
 [ 0.55603227]]


In [7]:
print(a.T)

[[-0.77526548  1.29765027 -1.77532732  0.32350956  0.55603227]]


In [8]:
print(np.dot(a, a.T))

[[ 0.60103656 -1.00602346  1.37634998 -0.2508058  -0.43107262]
 [-1.00602346  1.68389622 -2.30375397  0.41980227  0.72153542]
 [ 1.37634998 -2.30375397  3.15178709 -0.57433537 -0.98713928]
 [-0.2508058   0.41980227 -0.57433537  0.10465844  0.17988176]
 [-0.43107262  0.72153542 -0.98713928  0.17988176  0.30917188]]
